Add GitHub actions
chargebee/chargebee-ruby pull request #62
Opened 2021-11-25 09:45 UTC by ball-hayden

Adds GitHub actions to run tests and prevent issues such as #60.

GitHub actions is free for public repositories.

2022-02-07 08:08 UTC, ball-hayden commented
Bump @cb-yateshmathuria, @cb-goutham (as recent contributors)

2022-04-22 07:22 UTC, ball-hayden commented
Bump @cb-yateshmathuria, @cb-prajaktachavan

^ see my comment above. Please let me know if you'd like this PR or not.

2022-07-21 05:30 UTC, cb-prajaktachavan requested changes

2022-07-21 08:00 UTC, ball-hayden commented on .github/workflows/main.yml
> +        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
The issue was that the lockfile had the incorrect version number for `chargebee`.
This is now resolved.

2022-07-22 06:00 UTC, cb-prajaktachavan commented on .github/workflows/main.yml
> +        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
Hi @ball-hayden, Thanks for clarifying. Can we remove Gemfile.lock file? Other 2 files looks good to us. Let us know the reason behind committing this lock file.

2022-07-22 07:56 UTC, ball-hayden commented on .github/workflows/main.yml
> +        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
Hi @cb-prajaktachavan.

Please see the section here on why `Gemfile.lock` should be committed:
https://bundler.io/guides/faq.html#using-gemfiles-inside-gems

```
Q: Should I commit my `Gemfile.lock` when writing a gem?

A: Yes, you should commit it. The presence of a `Gemfile.lock` in a gem's repository ensures that a fresh checkout of the repository uses the exact same set of dependencies every time. We believe this makes repositories more friendly towards new and existing contributors. Ideally, anyone should be able to clone the repo, run `bundle install`, and have passing tests. If you don't check in your `Gemfile.lock`, new contributors can get different versions of your dependencies, and run into failing tests that they don't know how to fix.
```

2022-08-22 08:09 UTC, merged